

language: "en"

pipeline:
  - name: "tokenizer_whitespace"
  - name: "ner_crf"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_synonyms"
  - name: "intent_featurizer_count_vectors"
    OOV_token: oov
    token_pattern: (?u)\b\w+\b
  - name: "intent_classifier_tensorflow_embedding"
    # flag if to tokenize intents
    "intent_tokenization_flag": true
    "intent_split_symbol": "+"
policies:
  - name: "FormPolicy"












